version: "3.7"

services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - ./data/:/var/lib/postgresql/data
    ports:
      - 54321:5432

  api:
    build:
      context: ./docker
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./:/var/www/app
    depends_on:
      - postgres
    links:
      - postgres
    ports:
      - 8080:3000
